export enum ActionTypes {
  SAVE_ERROR_DESCRIPTION = 'SAVE_ERROR_DESCRIPTION',
  MAKE_LOGIN = 'MAKE_LOGIN',
  MAKE_LOGOUT = 'MAKE_LOGOUT',
  CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE',
  CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE',
  CHANGE_PLAYLIST_NAME = 'CHANGE_PLAYLIST_NAME',
  ERROR_FETCHING = 'ERROR_FETCHING',
  SAVE_USER_ID = 'SAVE_USER_ID',
  PUSH_NEW_TRACK = 'PUSH_NEW_TRACK',
  GENERATING_PLAYLIST = 'GENERATING_PLAYLIST',
  TRACKS_BEING_FETCHED = 'TRACKS_BEING_FETCHED',
  IS_DELETING = 'IS_DELETING',
}
